# Generated by Django 4.0 on 2022-02-18 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-published'], 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Опубликован'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.categorymodel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='article',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.articlemodel', verbose_name='Статья'),
        ),
    ]
