# Generated by Django 4.0.1 on 2022-02-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_contactwithauthormodel_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='photo1',
            field=models.ImageField(default='NotFound', upload_to='images'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='photo2',
            field=models.ImageField(default='NotFound', upload_to='images'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='photo3',
            field=models.ImageField(default='NotFound', upload_to='images'),
        ),
    ]
